# Generated by Django 2.0.3 on 2018-11-06 07:04

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_areainfo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='areainfo',
            managers=[
                ('area_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
